### PR TITLE
Launcher: Fix Actions not working in Launcher due to no .data attribute

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

This fixes an issue introduced by #2536 where the Launcher can't run any regular Actions but only support Applications.

The error was:

```python
Traceback (most recent call last):
  File "S:\openpype\OpenPype\openpype\tools\launcher\widgets.py", line 245, in on_clicked
    action.data.pop("start_last_workfile", None)
AttributeError: type object 'DebugShell' has no attribute 'data'
```

It's because `avalon.pipeline.Action` from which you build those actions has no `data` attribute.

---

### Additional context

Here are some example actions that would fail before this fix:
- [Explore Here Action](https://github.com/BigRoy/OpenPype/blob/colorbleed/openpype/modules/default_modules/colorbleed_module/launcher_actions/explore_here_action.py)
- [Debug Shell](https://github.com/BigRoy/OpenPype/blob/colorbleed/openpype/modules/default_modules/colorbleed_module/launcher_actions/debug_shell.py)

### CODE REVIEW

**Comment by BigRoy** [comment]
This might be improved by not duck typing but explicitly checking whether the `isinstance(action, Application)` since _if_ the Action would have a data attribute (even if for something else) it would still pass and likely not have that `"start_last_workfile"` key?

**Comment by iLLiCiTiT** [comment]
Now which is better https://github.com/pypeclub/OpenPype/pull/2659 :)

**Comment by BigRoy** [comment]
Closing this in favor of https://github.com/pypeclub/OpenPype/pull/2659
